version: "3.3"

services:
  # PHP service
  app-seed-name:
    image: php:8.1-fpm
    container_name: "app-${APP_SEED_NAME}"
    environment:
      SERVICE_NAME: app-${APP_SEED_NAME}
      SERVICE_TAGS: dev
    restart: unless-stopped
    build:
      context: ./config/php/
      dockerfile: Dockerfile
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./config/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - web
      - bank-network

  # NGINX service
  webserver-seed-name:
    image: nginx:alpine
    container_name: "webserver-${APP_SEED_NAME}"
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${APP_SEED_NAME}.rule=Host(`${APP_SEED_HOST}`)"
      - "traefik.http.routers.${APP_SEED_NAME}.entrypoints=websecure"
      - "traefik.http.routers.${APP_SEED_NAME}.tls.certresolver=ssl"
    volumes:
      - ./:/var/www
      - ./config/nginx/conf.d/:/etc/nginx/conf.d/
      - ./config/nginx/sites-available/:/etc/nginx/sites-available/
      - ./config/nginx/sites-enabled/:/etc/nginx/sites-enabled/
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
    links:
      - app-${APP_SEED_NAME}
    networks:
      - web
      - bank-network

  #MySQL Service
  db-seed-name:
    image: mysql:latest
    container_name: db-${APP_SEED_NAME}
    # restart: unless-stopped
    tty: true
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: ${APP_SEED_NAME}
      MYSQL_ROOT_PASSWORD: ${APP_SEED_MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${APP_SEED_MYSQL_USER}
      MYSQL_PASSWORD: ${APP_SEED_MYSQL_USER_PASSWORD}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./mysql/my.cnf:/etc/mysql/my.cnf
      - ./config/databases/mysql-files:/var/lib/mysql-files
      - ./data/databases:/var/lib/mysql
    networks:
      - bank-network
networks:
  web:
    external: true
  bank-network:
    driver: bridge